/**
 * Content for service-area pages generated by src/pages/fence-builder-[city]/index.astro.
 *
 * The six original pages (China Spring, Crawford, McGregor, Valley Mills,
 * Lorena, West) remain hand-authored static files. New towns go here.
 *
 * Every page must carry real local geography -- named roads, creeks, soil, and
 * communities. Thin "we also serve X" pages are what get filtered as doorway
 * content; the specificity is the whole point.
 */

export interface LocationFaq {
  question: string;
  answer: string;
}

export interface Location {
  city: string;
  county: string;
  /** Hero image basename in /public/images (expects `-800` variant too). */
  image: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  heroSubtitle: string;
  /** Two opening paragraphs (HTML allowed). */
  intro: string[];
  /** Four service cards. */
  cards: { heading: string; body: string }[];
  groundHeading: string;
  ground: string[];
  costHeading: string;
  cost: string[];
  areaHeading: string;
  area: string[];
  faqs: LocationFaq[];
  ctaHeading: string;
}

export const locations: Record<string, Location> = {
  hewitt: {
    city: 'Hewitt',
    county: 'McLennan County',
    image: 'city-3',
    title: 'Ranch and Acreage Fencing in Hewitt, TX',
    metaTitle: 'Fence Builder Hewitt TX | Ranch & Acreage | Brazos Ridge',
    metaDescription:
      'Fencing in Hewitt, TX. Barbed wire, pipe fence, and cross fencing for small acreage and horse property south of Waco. Free written estimates.',
    heroSubtitle:
      'South of Waco the city lots run out fast and the acreage starts. We build pipe, barbed wire, and cross fence for Hewitt places from two acres to two hundred.',
    intro: [
      'Hewitt sits on the blackland shelf south of Waco, where subdivisions along Hewitt Drive and Sun Valley Boulevard give way to small acreage within a mile or two. A lot of our work here is the in-between kind: someone has bought five or twenty acres off Spring Valley Road, wants a horse or a few head of cattle on it, and needs fence that does the job without looking like a feedlot from the county road.',
      'Brazos Ridge Fence Co. builds <a href="/barbed-wire-fence-waco/">barbed wire</a>, <a href="/pipe-fence-waco/">pipe fence</a>, and cross fencing across Hewitt and the rest of southern McLennan County. Estimates are free and in writing, and we run a 24/7 line for <a href="/fence-repair-waco/">fence repair</a> when stock gets out. Call us and we will walk the line with you.',
    ],
    cards: [
      {
        heading: 'Small Acreage Perimeter Fence',
        body: 'Most Hewitt places are 2 to 40 acres, which changes the math. We size the fence to what you are actually keeping in, and price cross fencing separately so you can phase it. See our guide on <a href="/blog/small-acreage-fencing-waco/">small acreage fencing</a> for the numbers.',
      },
      {
        heading: 'Horse-Safe Fencing',
        body: 'Barbed wire and horses are a bad mix on a small trap where a spooked animal has nowhere to go. We build pipe, no-climb net wire, and pipe-top combinations that hold a horse without cutting it.',
      },
      {
        heading: 'Pipe Fence and Entrances',
        body: 'Along the paved county roads through Hewitt, a welded pipe frontage fence and a proper entrance do a lot for the place. We build <a href="/ranch-entrance-gates-waco/">entrance gates</a> sized for a truck and trailer.',
      },
      {
        heading: 'Cross Fencing and Traps',
        body: 'Rotating even two small pastures beats grazing one flat. We lay out cross fence and catch pens so you can move stock by yourself without a second set of hands.',
      },
    ],
    groundHeading: 'Setting Posts in Hewitt Blackland',
    ground: [
      'Hewitt is squarely in the Houston Black clay that runs down the middle of McLennan County. It is good dirt for grass and hard dirt for posts. When it dries in August it opens cracks you can lose a tape measure in, and every one of those cracks lets a post work a little looser.',
      'We set corner and brace posts deep and tamp in lifts rather than trusting a shovel of concrete at the top. On a small place where every corner is close to a road or a house, that difference shows up within three summers. Our guide on <a href="/blog/fence-posts-in-clay-soil/">setting posts in clay soil</a> walks through why.',
      'Drainage matters here too. Several Hewitt neighborhoods sit uphill of the pastures below them, so a fence line crossing a draw takes more runoff than the acreage alone would suggest. We build those low spots as gaps that can be rehung rather than stretches that wash out.',
    ],
    costHeading: 'What Fencing Costs Around Hewitt',
    cost: [
      'Five strand barbed wire on clean ground runs $2.50 to $5.50 per foot. Net wire for horses or goats runs $3.50 to $8. Pipe fence, which a fair number of Hewitt places want along the road frontage, runs $12 to $28 per foot depending on pipe size.',
      'On a small tract the per-foot number matters less than the corner count. A twenty acre square needs roughly 3,700 feet of perimeter and four corners; the same twenty acres in a long narrow strip can need half again as much fence. We measure before we quote. For the full breakdown see our <a href="/ranch-fence-cost/">ranch fence cost guide</a>.',
    ],
    areaHeading: 'Serving Hewitt and Southern McLennan County',
    area: [
      'We cover Hewitt along with <a href="/fence-builder-woodway/">Woodway</a>, <a href="/fence-builder-robinson/">Robinson</a>, and <a href="/fence-builder-lorena/">Lorena</a>, so a job here sits in the middle of our normal week. Most of southern McLennan County is inside a twenty minute drive of our yard.',
      'If a storm comes through and drops a limb across your fence, or stock gets out toward Old Hewitt Road, call any hour. We patch first so nothing is loose on pavement, then come back and build the permanent repair.',
    ],
    faqs: [
      {
        question: 'Do you build fence for small acreage in Hewitt, or only big ranches?',
        answer:
          'We build both. A good share of our Hewitt work is 2 to 40 acre places wanting a perimeter, a cross fence, and an entrance. Small jobs get the same walked line and the same written per-foot price as a full section.',
      },
      {
        question: 'What is the best fence for a couple of horses on a small Hewitt place?',
        answer:
          'On a small trap we steer people away from barbed wire. No-climb net wire with a pipe or wood top rail is the usual answer, and pipe fence where budget allows. It costs more per foot than barbed wire but a vet bill for a wire cut costs more than the difference.',
      },
      {
        question: 'Can you fence around an existing house and septic field?',
        answer:
          'Yes, and it is worth planning before we dig. We locate the septic field and lateral lines first, then lay the fence so no post lands in them. On newer Hewitt builds the as-built drawing usually shows enough to work from.',
      },
      {
        question: 'How much fence do I need for 10 acres in Hewitt?',
        answer:
          'A square 10 acres is about 2,640 feet of perimeter. Odd-shaped tracts run longer, sometimes 3,200 feet or more for the same acreage. We measure the actual shape and quote the real footage rather than the acreage math.',
      },
    ],
    ctaHeading: 'Fencing a Place Around Hewitt?',
  },

  woodway: {
    city: 'Woodway',
    county: 'McLennan County',
    image: 'city-4',
    title: 'Ranch and Estate Fencing in Woodway, TX',
    metaTitle: 'Fence Builder Woodway TX | Estate & Ranch | Brazos Ridge',
    metaDescription:
      'Fencing in Woodway, TX. Pipe fence, custom entrances, and acreage fencing along the Bosque bluffs west of Waco. Free written estimates.',
    heroSubtitle:
      'Woodway acreage runs from flat blackland to the limestone breaks above the Bosque. We build pipe fence, custom entrances, and perimeter fence that fits both.',
    intro: [
      'Woodway sits west of Waco where the prairie starts falling off toward the Bosque River. Places along Ritchie Road and out toward Estates Drive tend to be larger tracts with a house on them, and the fencing question is usually as much about how the front of the place looks as it is about holding stock.',
      'We build welded <a href="/pipe-fence-waco/">pipe fence</a>, custom <a href="/ranch-entrance-gates-waco/">ranch entrance gates</a>, and conventional <a href="/barbed-wire-fence-waco/">barbed wire</a> across Woodway and the country west of it. Every estimate is free and in writing, with the pipe work and the wire work priced separately so you can see where the money goes.',
    ],
    cards: [
      {
        heading: 'Pipe Fence and Frontage',
        body: 'Welded pipe along the road frontage and wire on the back lines is the most common Woodway build. It puts the money where it shows and holds stock everywhere else. Pipe runs $12 to $28 per foot depending on size.',
      },
      {
        heading: 'Custom Entrances and Columns',
        body: 'A pipe arch, stone columns, and a gate that swings true set the tone before anyone reaches the house. We size the opening for stock trailers, not just pickups, and wire in solar openers.',
      },
      {
        heading: 'Fencing the Bosque Breaks',
        body: 'West of town the ground drops toward the river and the limestone comes up. We bring rock bits and set corners to grade so a fence on a slope does not walk downhill over the years.',
      },
      {
        heading: 'Cattle Guards',
        body: 'A cattle guard beats a gate somebody has to get out and open twice a day. We set them on proper footings so the ends do not settle and the rails stay level with the drive.',
      },
    ],
    groundHeading: 'Building Fence on the Woodway Breaks',
    ground: [
      'Woodway straddles two different fencing problems. On the flat east side you are in blackland clay that swells and shrinks. Move west toward the bluffs and you hit shallow limestone where an auger stops dead at eighteen inches.',
      'We carry both setups on the truck. In the clay it is depth and tamping. In the rock it is a rock bit and, where the hole simply will not go deeper, a shorter post set in concrete with the brace geometry adjusted to compensate. Our guide on <a href="/blog/fence-posts-in-rocky-ground/">setting posts in rocky ground</a> covers the trade-offs.',
      'Grade is the other Woodway factor. A fence that crosses a slope wants to pull its corners downhill, so we brace for the direction of pull rather than treating every corner the same.',
    ],
    costHeading: 'What Fencing Costs Around Woodway',
    cost: [
      'A typical Woodway job mixes materials. Pipe fence on the frontage at $12 to $28 per foot, barbed wire or net wire on the balance at $2.50 to $8, and an entrance that runs anywhere from $3,500 for a straightforward pipe gate to well past $15,000 for stone columns and a custom arch.',
      'Rock drilling adds cost on the west side, usually $15 to $40 per hole over a normal set. We flag that in the estimate rather than discovering it mid-job. The <a href="/ranch-fence-cost/">ranch fence cost guide</a> has the full per-foot breakdown.',
    ],
    areaHeading: 'Serving Woodway and West McLennan County',
    area: [
      'We work Woodway alongside <a href="/fence-builder-china-spring/">China Spring</a>, <a href="/fence-builder-hewitt/">Hewitt</a>, and <a href="/fence-builder-mcgregor/">McGregor</a>. The whole west side of the county is a normal day for our crews.',
      'For storm damage or a gate that quit latching, call any hour. Most repairs on this side of town we can reach the same day.',
    ],
    faqs: [
      {
        question: 'What does a pipe entrance cost in Woodway?',
        answer:
          'A straightforward welded pipe entrance with a 16 foot gate generally runs $3,500 to $7,000 installed. Add stone columns, a taller overhead arch, or a solar opener and it climbs from there, with full custom entries running past $15,000. We quote the gate, the columns, and the opener as separate lines.',
      },
      {
        question: 'Can you build fence on the slopes above the Bosque?',
        answer:
          'Yes. Slope work is mostly a bracing question. We set corners to resist the downhill pull and step the fence to grade so there is no gap under the bottom wire where the ground falls away. Shallow limestone on those bluffs means rock bits, which we price into the estimate.',
      },
      {
        question: 'Do you install cattle guards?',
        answer:
          'We do, including the concrete footings and wing walls. A properly set guard on a drive that sees truck-and-trailer traffic runs roughly $2,500 to $6,000 depending on width and rating. Skimping on the footings is what makes a guard settle and go crooked.',
      },
      {
        question: 'Will you match fence to what my neighbor already has?',
        answer:
          'Usually, and on a shared line it is worth doing. We match wire class, post spacing, and height so the two runs read as one fence. If the neighbor line is in poor shape we will tell you what it would take to bring it up rather than tying good fence to bad.',
      },
    ],
    ctaHeading: 'Fencing a Place Around Woodway?',
  },

  robinson: {
    city: 'Robinson',
    county: 'McLennan County',
    image: 'city-5',
    title: 'Farm and Ranch Fencing in Robinson, TX',
    metaTitle: 'Fence Builder Robinson TX | Farm & Ranch | Brazos Ridge',
    metaDescription:
      'Farm and ranch fencing in Robinson, TX. Barbed wire, net wire, and river bottom fencing south of Waco. Free written estimates.',
    heroSubtitle:
      'Robinson runs from blackland farm ground to the Brazos bottoms. We build barbed wire, net wire, and water gaps that survive the river coming up.',
    intro: [
      'Robinson sits between Waco and the Brazos River, and the fencing changes depending on which side of town you are on. Up along Old Robinson Road and FM 2113 it is farm ground and pasture on deep black clay. Drop east toward the river and you are in bottomland that floods, grows brush fast, and eats fence.',
      'Brazos Ridge Fence Co. builds <a href="/barbed-wire-fence-waco/">barbed wire</a>, net wire, and <a href="/pipe-fence-waco/">pipe corrals</a> across Robinson and the south end of McLennan County. We quote a walked line in writing, and our <a href="/fence-repair-waco/">emergency line</a> runs around the clock for cattle out and storm damage.',
    ],
    cards: [
      {
        heading: 'Barbed Wire on Farm Ground',
        body: 'Five and six strand barbed wire is still the workhorse on Robinson pasture. We stretch it tight on braced corners and set the bottom wire high enough to run a shredder under without cutting it.',
      },
      {
        heading: 'Brazos Bottom Water Gaps',
        body: 'Any fence crossing a draw to the river needs a gap built to fail on purpose. We hang breakaway panels so a rise takes the panel and leaves the fence, which turns a week of rebuilding into an hour of rehanging. See our <a href="/blog/water-gap-fence/">water gap guide</a>.',
      },
      {
        heading: 'Brush Clearing',
        body: 'Bottomland grows mesquite, hackberry, and greenbrier faster than anywhere else in the county. We clear the line before we build and price the clearing separately so you can see it.',
      },
      {
        heading: 'Working Pens and Corrals',
        body: 'Welded pipe pens that hold up on shipping day. We lay out the crowd pen and alley so one person can work cattle without a crew standing around.',
      },
    ],
    groundHeading: 'Fencing the Blackland and the Bottoms',
    ground: [
      'The blackland side of Robinson is classic Houston Black clay. It holds a post well when it is set deep and tamped properly, and it heaves anything set shallow. We go deeper on corners here than most crews bother with, because pulling a heaved brace in year four costs more than the extra foot of hole did.',
      'The bottom side is a different animal. Sandy loam over gravel near the river holds less, so brace posts get larger diameter and often concrete. Flood is the design case rather than the exception, and anything in the floodway gets built to give way cleanly.',
      'Brush is the third factor. A line cleared once and never touched grows back into the fence within four or five seasons, which is how a good fence turns into a repair call. Our <a href="/blog/clearing-fence-line-brush/">fence line clearing guide</a> covers keeping it open.',
    ],
    costHeading: 'What Fencing Costs Around Robinson',
    cost: [
      'On open farm ground, five strand barbed wire runs $2.50 to $5.50 per foot, which puts a mile between roughly $13,000 and $29,000. Net wire for goats or a tighter cattle fence runs $3.50 to $8.',
      'Bottomland costs more, and it is honest to say so up front. Clearing, larger brace material, and water gap construction can add 20 to 40 percent over the same footage on clean prairie. We break those out as line items in the estimate rather than burying them in the per-foot price. Full numbers are in the <a href="/ranch-fence-cost/">ranch fence cost guide</a>.',
    ],
    areaHeading: 'Serving Robinson and the Brazos Bottoms',
    area: [
      'We cover Robinson along with <a href="/fence-builder-hewitt/">Hewitt</a>, <a href="/fence-builder-lorena/">Lorena</a>, and down toward <a href="/fence-builder-marlin/">Marlin</a> in Falls County. The river corridor south of Waco is regular ground for us.',
      'After a rise on the Brazos we get a run of calls at once, so if water has been up, call early rather than waiting to see how bad it is.',
    ],
    faqs: [
      {
        question: 'How do you fence across a creek in the Brazos bottoms?',
        answer:
          'With a breakaway water gap, not a fixed fence. We hang a panel from a cable or a swing arm so high water lifts it out of the way or carries it off a short tether instead of tearing out the anchored fence on both banks. Rehanging a gap takes about an hour; rebuilding a washed-out stretch takes days.',
      },
      {
        question: 'Does fence in the river bottom cost more than on the prairie?',
        answer:
          'Yes, typically 20 to 40 percent more for the same footage. Brush clearing, heavier brace material, and water gap construction are the three drivers. We list them separately in the estimate so you can decide what to do now and what to phase.',
      },
      {
        question: 'How often will bottomland fence need work?',
        answer:
          'Plan on walking it after every significant rise and clearing brush off the line every three or four years. A bottom fence that gets that attention lasts nearly as long as one on high ground. One that gets ignored is usually a rebuild inside a decade.',
      },
      {
        question: 'Can you build working pens as part of a fencing job?',
        answer:
          'Yes, and doing it in the same trip saves a mobilization. We build welded pipe pens, crowd tubs, and alleys sized to your herd and your trailer. Most sets we build in the Robinson area run $8,000 to $25,000 depending on size and whether you want a squeeze chute framed in.',
      },
    ],
    ctaHeading: 'Fencing a Place Around Robinson?',
  },

  clifton: {
    city: 'Clifton',
    county: 'Bosque County',
    image: 'city-6',
    title: 'Ranch Fencing in Clifton, TX',
    metaTitle: 'Ranch Fencing Clifton TX | Bosque County | Brazos Ridge',
    metaDescription:
      'Ranch fencing in Clifton, TX. Game fence, net wire for sheep and goats, and pipe fence across Bosque County limestone. Free written estimates.',
    heroSubtitle:
      'Clifton is limestone and cedar country with a long history of sheep and goats. We build net wire, game fence, and pipe that holds on hard ground.',
    intro: [
      'Clifton sits on the Bosque River in the middle of Bosque County, in the hill country that Norwegian settlers took up in the 1850s. The ground here is nothing like the Waco blackland twenty five miles east. It is shallow soil over limestone, cedar in the draws, and enough grade that a fence line rarely runs flat for long.',
      'That country has run sheep and goats for well over a century, and it still does alongside cattle and increasingly whitetail behind <a href="/game-fence-installation-waco/">high fence</a>. We build net wire, <a href="/barbed-wire-fence-waco/">barbed wire</a>, and <a href="/pipe-fence-waco/">pipe fence</a> throughout Bosque County, with free written estimates.',
    ],
    cards: [
      {
        heading: 'Net Wire for Sheep and Goats',
        body: 'Goats are the hardest animal in Texas to keep behind a fence. Fixed knot net wire with tight spacing at the bottom is the answer, not more strands of barbed wire. Our <a href="/blog/fence-for-goats-and-sheep/">goat and sheep fencing guide</a> covers spacing and cost.',
      },
      {
        heading: 'High Game Fence',
        body: 'A growing share of Bosque County acreage is managed for whitetail and exotics. We build 8 foot fixed knot game fence over rolling limestone, including the grade changes and draws that make it tricky.',
      },
      {
        heading: 'Cedar Clearing',
        body: 'Ashe juniper takes a fence line back fast out here. We clear the line ahead of the build and price the clearing as its own item so you can see what it costs.',
      },
      {
        heading: 'Pipe Fence and Corrals',
        body: 'Welded pipe for pens, corrals, and road frontage. On shallow rock, pipe set in concrete often outperforms wood posts that cannot get depth.',
      },
    ],
    groundHeading: 'Building Fence on Bosque County Limestone',
    ground: [
      'The fencing problem around Clifton is depth. In a lot of places you have twelve to twenty inches of soil sitting on solid limestone, and a post that wants to go three and a half feet down simply is not going to.',
      'We drill. A hydraulic auger with a carbide rock bit gets through most of what is out here, and where it will not, we set shorter posts in concrete and change the brace geometry to make up for the lost depth. What we do not do is set a shallow post in dirt and call it good, because that is the corner that pulls in year two.',
      'Grade compounds it. A fence dropping off a ridge into a draw pulls hard downhill, so corners at the top of a grade need bracing sized for the pull rather than the standard assembly. Our <a href="/blog/h-brace-fence-corners/">H-brace guide</a> explains the geometry.',
    ],
    costHeading: 'What Fencing Costs Around Clifton',
    cost: [
      'Net wire for sheep and goats runs $3.50 to $8 per foot depending on wire class and how much clearing the line needs. Barbed wire runs $2.50 to $5.50, and game fence $4.50 to $10.',
      'Rock drilling is the Bosque County variable. Depending on how much limestone we hit, expect $15 to $40 per hole over a normal set, which on a mile of fence with posts every twelve feet is real money. We walk the line and probe before quoting so the number in the estimate is the number on the invoice. See the <a href="/ranch-fence-cost/">ranch fence cost guide</a> for the full picture.',
    ],
    areaHeading: 'Serving Clifton and Bosque County',
    area: [
      'We work Clifton along with <a href="/fence-builder-meridian/">Meridian</a>, <a href="/fence-builder-valley-mills/">Valley Mills</a>, and the ranch country along SH 6 and FM 219. Bosque County is a normal run for us out of Waco.',
      'Call any hour if stock is out or a storm has taken a line down. We patch first so nothing is loose on the highway, then schedule the permanent repair.',
    ],
    faqs: [
      {
        question: 'What fence actually holds goats around Clifton?',
        answer:
          'Fixed knot net wire, 47 inches or taller, with vertical stays no more than 6 inches apart at the bottom. Barbed wire does not hold goats no matter how many strands you run, and hinge joint wire lets them push through the bottom squares. Expect $3.50 to $8 per foot installed.',
      },
      {
        question: 'How do you set posts where there is only a foot of soil?',
        answer:
          'We drill into the limestone with a carbide rock bit and set the post in the rock itself, which actually holds better than deep soil once it is grouted or concreted in. Where the rock is too hard or too shallow, we shorten the post, widen the brace, and adjust the assembly so the geometry still carries the load.',
      },
      {
        question: 'Do you build game fence in Bosque County?',
        answer:
          'Regularly. Eight foot fixed knot game fence runs $4.50 to $10 per foot here, with the rolling ground and cedar clearing pushing toward the upper half of that range. We handle the clearing, the grade changes, and the water gaps across the draws.',
      },
      {
        question: 'How much does cedar clearing add to a fence job?',
        answer:
          'On a heavily cedared line, clearing typically runs $1.50 to $4 per foot on top of the fence itself, depending on stem size and whether you want the material burned, mulched, or windrowed. A cleared line builds straighter and needs far less maintenance, so it is rarely worth skipping.',
      },
    ],
    ctaHeading: 'Fencing a Place Around Clifton?',
  },

  meridian: {
    city: 'Meridian',
    county: 'Bosque County',
    image: 'city-2',
    title: 'Ranch Fencing in Meridian, TX',
    metaTitle: 'Ranch Fencing Meridian TX | Bosque County | Brazos Ridge',
    metaDescription:
      'Ranch fencing in Meridian, TX. Game fence, barbed wire, and pipe built for Bosque County hills and shallow limestone. Free written estimates.',
    heroSubtitle:
      'Meridian country is cedar, limestone, and creek draws. We build game fence, barbed wire, and pipe that accounts for all three.',
    intro: [
      'Meridian is the Bosque County seat, sitting where Meridian Creek comes down out of the hills to meet the Bosque River. SH 6 and SH 22 cross here, and the ranch country in every direction is broken up by draws, cedar brakes, and ledges of limestone that surface without warning.',
      'We build <a href="/game-fence-installation-waco/">game fence</a>, <a href="/barbed-wire-fence-waco/">barbed wire</a>, and <a href="/pipe-fence-waco/">pipe fence</a> across the Meridian area, along with the water gaps that keep a creek crossing from becoming an annual rebuild. Estimates are free and in writing.',
    ],
    cards: [
      {
        heading: 'High Game Fence',
        body: 'Meridian has become serious whitetail country. We build 8 foot fixed knot game fence over rough ground, handling the grade breaks and draws where a fence wants to leave a gap underneath.',
      },
      {
        heading: 'Creek Draw Water Gaps',
        body: 'Meridian Creek and the draws feeding it flash hard. We build breakaway gaps at every crossing so high water takes a panel rather than a stretch of fence.',
      },
      {
        heading: 'Barbed Wire on Hill Pasture',
        body: 'Five and six strand barbed wire built to grade, with corners braced for the direction of pull rather than a one-size assembly. On this ground that distinction is what makes a fence last.',
      },
      {
        heading: 'Cedar and Brush Clearing',
        body: 'Ashe juniper is the standing crop out here whether you want it or not. We clear the fence line first, priced separately, so the fence runs straight and stays reachable.',
      },
    ],
    groundHeading: 'Fencing the Meridian Hills',
    ground: [
      'Meridian country is where a crew earns its money. Soil depth changes in the space of a single fence run, so the same line might take a normal auger for two hundred feet and a rock bit for the next fifty.',
      'We probe the line before quoting rather than guessing, because a rock surprise discovered halfway through is how change orders happen. Where the limestone is close, we drill and set in the rock. Where there is depth, we tamp in lifts. Either way the corner has to hold thousands of pounds of standing tension.',
      'Grade is constant here. Fences run up and down ridges, and a corner sitting at the top of a pull needs a heavier assembly than the same corner on flat ground. We also step the wire to follow the ground on grade breaks so deer and hogs do not have a gap to crawl under.',
    ],
    costHeading: 'What Fencing Costs Around Meridian',
    cost: [
      'Barbed wire runs $2.50 to $5.50 per foot on ground that is not too broken. Game fence runs $4.50 to $10, and on Meridian terrain most jobs land in the upper half of that because of clearing and rock.',
      'Two line items move the number here more than anywhere else we work: cedar clearing at $1.50 to $4 per foot on a heavy line, and rock drilling at $15 to $40 per hole. We put both in the written estimate as their own lines. The <a href="/ranch-fence-cost/">ranch fence cost guide</a> has the rest.',
    ],
    areaHeading: 'Serving Meridian and the Bosque Hills',
    area: [
      'We cover Meridian, <a href="/fence-builder-clifton/">Clifton</a>, <a href="/fence-builder-valley-mills/">Valley Mills</a>, and the country along SH 6 and SH 22. Bosque County work runs on our normal schedule out of Waco.',
      'When a storm rolls through the hills and drops timber across a line, or stock gets out toward the highway, call any hour. We patch first and rebuild properly after.',
    ],
    faqs: [
      {
        question: 'How much does game fence cost around Meridian?',
        answer:
          'Eight foot fixed knot game fence generally runs $4.50 to $10 per foot here, and most Meridian jobs land in the upper half of that range. Cedar clearing and rock drilling are the reasons. A mile of high fence on this ground commonly works out between $30,000 and $53,000.',
      },
      {
        question: 'How do you keep deer and hogs from going under a fence on rough ground?',
        answer:
          'By stepping the fence to follow the ground instead of running it straight across a dip. Every low spot gets the wire brought down to grade, and on game fence we add a barbed bottom strand or a skirt where the ground is uneven enough that a hog could root under.',
      },
      {
        question: 'What happens when Meridian Creek comes up over a fence line?',
        answer:
          'That is what a breakaway water gap is for. We hang panels at every crossing so a rise carries the panel off rather than ripping out anchored fence on both banks. After the water drops you rehang the panel in about an hour.',
      },
      {
        question: 'Do you charge to come look at a place this far out?',
        answer:
          'No. Estimates are free and in writing anywhere in McLennan, Bosque, or Falls County, Meridian included. We walk the line with you, measure the real footage, and price it by the foot with clearing and gates as separate lines.',
      },
    ],
    ctaHeading: 'Fencing a Place Around Meridian?',
  },

  marlin: {
    city: 'Marlin',
    county: 'Falls County',
    image: 'city-1',
    title: 'Farm and Ranch Fencing in Marlin, TX',
    metaTitle: 'Fence Builder Marlin TX | Falls County | Brazos Ridge Fence',
    metaDescription:
      'Farm and ranch fencing in Marlin, TX. Barbed wire, net wire, and Brazos bottom water gaps across Falls County. Free written estimates.',
    heroSubtitle:
      'Falls County is deep blackland and Brazos bottom. We build barbed wire, net wire, and water gaps for cattle and hay country southeast of Waco.',
    intro: [
      'Marlin is the Falls County seat, sitting in the deep blackland southeast of Waco where the Brazos runs down toward the falls the county is named for. This is cotton and cattle country, mostly big open fields and pasture with the river bottom on the east side, and the fence problems here are the blackland problems at their most extreme.',
      'Brazos Ridge Fence Co. builds <a href="/barbed-wire-fence-waco/">barbed wire</a>, net wire, and <a href="/pipe-fence-waco/">pipe corrals</a> throughout Falls County. Every estimate is free and in writing, and our <a href="/fence-repair-waco/">emergency line</a> answers around the clock when cattle get out on SH 6 or FM 147.',
    ],
    cards: [
      {
        heading: 'Barbed Wire for Cattle Country',
        body: 'Five and six strand barbed wire on braced corners, stretched tight. On the long straight runs Falls County allows, we set line braces roughly every 650 feet so no single pull carries the whole run.',
      },
      {
        heading: 'Brazos Bottom Water Gaps',
        body: 'The river and its draws take out any fence built rigid across them. We build breakaway gaps that give way clean. See our <a href="/blog/water-gap-fence/">water gap guide</a> for how they go together.',
      },
      {
        heading: 'Working Pens and Corrals',
        body: 'Welded pipe pens sized for the herd and the trailer, laid out so one person can pen and load without help on shipping day.',
      },
      {
        heading: 'Hay Meadow Fencing',
        body: 'Fence around hay ground has different requirements than pasture fence. We set the bottom wire so equipment can work close to the line without cutting it, and place gates where a baler can actually turn.',
      },
    ],
    groundHeading: 'Fencing Falls County Blackland',
    ground: [
      'Falls County has some of the deepest black clay in Central Texas, and it moves more than anything we work in. A wet spring swells it until posts get pushed sideways; an August drought shrinks it until you can drop a fence staple down the crack beside a post.',
      'That cycle is what pulls corners and leans line posts here, not the wire tension by itself. We set corner and brace posts well below the zone that moves, tamp in lifts rather than backfilling loose, and use larger diameter brace material than the same job would need on lighter ground.',
      'Drought years are hard on Falls County fence in particular. Our guide on <a href="/blog/drought-fence-problems/">drought fence problems</a> covers what to watch for as the ground opens up.',
    ],
    costHeading: 'What Fencing Costs Around Marlin',
    cost: [
      'Five strand barbed wire on clean open ground runs $2.50 to $5.50 per foot, which puts a mile between roughly $13,000 and $29,000. Net wire runs $3.50 to $8. Falls County has a lot of long straight lines and few obstacles, so jobs here often land at the lower end of those ranges.',
      'The bottom ground is the exception. Clearing, heavier braces, and water gaps push the same footage up substantially. We break those out as separate lines. Full numbers are in the <a href="/ranch-fence-cost/">ranch fence cost guide</a>.',
    ],
    areaHeading: 'Serving Marlin and Falls County',
    area: [
      'We cover Marlin and Falls County along with <a href="/fence-builder-robinson/">Robinson</a> and <a href="/fence-builder-lorena/">Lorena</a> to the north. The run down SH 6 is part of our normal week.',
      'Cattle out on SH 6 or FM 147 is a liability problem before it is a fence problem, so call the moment you know. We patch first and build the permanent repair after.',
    ],
    faqs: [
      {
        question: 'How much does barbed wire fence cost per foot around Marlin?',
        answer:
          'Five strand barbed wire on open Falls County ground typically runs $2.50 to $5.50 per foot installed. The long straight runs and light clearing common here often put jobs at the lower end of that. We walk the line and put exact footage and pricing in a free written estimate.',
      },
      {
        question: 'Why do fence posts lean so badly in Falls County?',
        answer:
          'Deep black clay. It swells when wet and shrinks hard when dry, and that cycle works a post loose a little at a time regardless of wire tension. The fix is depth and proper tamping on the corners and braces, plus larger brace material than lighter soils need.',
      },
      {
        question: 'Do you build fence in the Brazos bottom east of Marlin?',
        answer:
          'Yes. Bottom work needs breakaway water gaps at every crossing, heavier brace material, and brush clearing before the build. It costs meaningfully more per foot than the same fence on open prairie, and we itemize those extras rather than folding them into one number.',
      },
      {
        question: 'Can you fence around hay meadows without getting in the way of equipment?',
        answer:
          'That is mostly a layout question and worth talking through before we build. We set the bottom wire at a height that lets a shredder work close without catching, keep braces out of turn rows where we can, and put gates where a tractor and baler can actually swing through.',
      },
    ],
    ctaHeading: 'Fencing a Place Around Marlin?',
  },
};
